"""GENERATING_IAC stage (CLAUDE.md Section 8 / Section 10 / F5).

Generates the Terraform (or CDK) for this version, records the artifact on
the version record, then opens the F5 git flow: branch -> commit -> PR. The
PR is a pipeline trigger, not a human review request (F5) — this handler
never merges it. The branch name returned here becomes every subsequent
CodeBuild stage's SourceVersion (see deployment_workflow.json) up to
POLICY_CHECK, which merges (PASS) or closes (BLOCK) it — see policy_check.py.
"""

from __future__ import annotations

from typing import Any

from lambda_handlers.common import (
    StageFailure,
    deployment_status_store,
    git_provider,
    iac_generator,
    registry_store,
    require,
    require_git_repo_url,
    run,
)


def _branch_name(agent_id: str, version: int, deployment_id: str) -> str:
    return f"feature/agent-{agent_id}-v{version}-{deployment_id}"


async def _generate_and_open_pr(
    agent_id: str, tenant_id: str, version: int, deployment_id: str
) -> dict[str, Any]:
    version_record = await registry_store.get_version_detail(tenant_id, agent_id, version)
    if version_record is None:
        raise StageFailure(f"Version {version} of agent {agent_id!r} not found")

    result = await iac_generator.generate(agent_id, version, version_record.configuration)
    await registry_store.record_iac_artifact(
        tenant_id=tenant_id,
        agent_id=agent_id,
        version=version,
        iac_version=result.iac_version,
        iac_s3_key=result.s3_key,
    )

    git_repo_url = require_git_repo_url()
    branch = _branch_name(agent_id, version, deployment_id)
    await git_provider.create_branch(git_repo_url, branch)
    await git_provider.commit_files(
        git_repo_url,
        branch,
        result.files,
        message=f"agent {agent_id} v{version} — generated by Panasa Agent Builder",
    )
    pr_id = await git_provider.create_pull_request(
        git_repo_url,
        branch,
        title=f"[Panasa Auto] {agent_id} v{version} — Deploy",
        description=f"Agent: {agent_id} | Version: {version} | Deployment: {deployment_id}",
    )

    return {
        "iacVersion": result.iac_version,
        "s3Key": result.s3_key,
        "modules": result.modules,
        "branch": branch,
        "prId": pr_id,
    }


def handler(event: dict[str, Any], _context: Any) -> dict[str, Any]:
    agent_id, tenant_id = require(event, "agentId", "tenantId")
    version = int(event["version"])
    deployment_id = event["deploymentId"]

    result = run(_generate_and_open_pr(agent_id, tenant_id, version, deployment_id))

    run(
        deployment_status_store.update_stage(
            agent_id=agent_id,
            deployment_id=deployment_id,
            stage="GENERATING_IAC",
            stage_status="PASSED",
            output_summary=(
                f"Terraform generated: {len(result['modules'])} module(s), "
                f"PR {result['prId']} opened"
            ),
            overall_status="SECURITY_SCANNING",
        )
    )
    return result
